llm_endpoints:
  - name: "Llama 3.2 3b"
    url: "http://pappai01.bs.ch:11434/v1/completions"
    description: "KI Plattform LLama 3.2 3b"

  - name: "LLama 3.1 70b"
    url: "http://pappai01.bs.ch:11434/v1/completions"
    description: "KI Plattform LLama 3.1 70b"

  - name: "LLama 3.1 Nemotron 70b"
    url: "http://pappai01.bs.ch:11434/v1/completions"
    description: "KI Plattform LLama 3.1 Nemotron 70b"

  - name: "Gemma 2 27b"
    url: "http://pappai01.bs.ch:11434/v1/completions"
    description: "KI Plattform Gemma 2 27b"

  - name: "Qwen 2.5 0.5b"
    url: "http://pappai01.bs.ch:11434/v1/completions"
    description: "KI Plattform Qwen 2.5 0.5b"

  - name: "Qwen 2.5 1.5b"
    url: "http://pappai01.bs.ch:11434/v1/completions"
    description: "KI Plattform Qwen 2.5 1.5b"

  - name: "Qwen 2.5 7b"
    url: "http://pappai01.bs.ch:11434/v1/completions"
    description: "KI Plattform Qwen 2.5 7b"

  - name: "Qwen 2.5 14b"
    url: "http://pappai01.bs.ch:11434/v1/completions"
    description: "KI Plattform Qwen 2.5 14b"

  - name: "Qwen 2.5 32b"
    url: "http://pappai01.bs.ch:11434/v1/completions"
    description: "KI Plattform Qwen 2.5 32b"

  - name: "Qwen 2.5 72b"
    url: "http://pappai01.bs.ch:11434/v1/completions"
    description: "KI Plattform Qwen 2.5 72b"

  - name: "Aya Expanse 8b"
    url: "http://pappai01.bs.ch:11434/v1/completions"
    description: "KI Plattform Aya Expanse 8b"

  - name: "Aya Expanse 32b"
    url: "http://pappai01.bs.ch:11434/v1/completions"
    description: "KI Plattform Aya Expanse 32b"